In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
import warnings 

In [4]:
warnings.filterwarnings("ignore")

In [5]:
clist=["Blue","Red","Black","Yellow"]

In [6]:
clist

['Blue', 'Red', 'Black', 'Yellow']

In [10]:
pd.DataFrame(clist,columns=["Colours"])

Colours
0    Blue
1     Red
2   Black
3  Yellow

In [13]:
df=pd.DataFrame(clist,columns=["Colours"])

In [14]:
df

Colours
0    Blue
1     Red
2   Black
3  Yellow

In [15]:
from sklearn.preprocessing import OneHotEncoder

In [16]:
ohe=OneHotEncoder()

In [19]:
ohe.fit(df[["Colours"]])

OneHotEncoder()

In [20]:
ohe.transform(df[["Colours"]])

<4x4 sparse matrix of type '<class 'numpy.float64'>'
	with 4 stored elements in Compressed Sparse Row format>

In [21]:
ohe.transform(df[["Colours"]]).toarray()

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.]])

In [22]:
df1=ohe.transform(df[["Colours"]]).toarray()

In [23]:
df1

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.]])

In [24]:
ohe.categories_

[array(['Black', 'Blue', 'Red', 'Yellow'], dtype=object)]

In [27]:
pd.DataFrame(df1,columns=clist,dtype="int")

Blue  Red  Black  Yellow
0     0    1      0       0
1     0    0      1       0
2     1    0      0       0
3     0    0      0       1

### 

In [29]:
dftw=pd.read_csv(R"C:\Users\ny691\Downloads\DATASETS\DATASETS\Outlier Detection Dataset\Onehotencoding dataset (2)\Onehotencoding dataset\township.csv")

In [30]:
dftw

town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

In [31]:
dftw["town"]

0     monroe township
1     monroe township
2     monroe township
3     monroe township
4     monroe township
5        west windsor
6        west windsor
7        west windsor
8        west windsor
9         robinsville
10        robinsville
11        robinsville
12        robinsville
Name: town, dtype: object

In [32]:
from sklearn.preprocessing import OneHotEncoder

In [33]:
ohe1=OneHotEncoder()

In [34]:
ohe1.fit(dftw[["town"]])

OneHotEncoder()

In [35]:
ohe1.transform(dftw[["town"]])

<13x3 sparse matrix of type '<class 'numpy.float64'>'
	with 13 stored elements in Compressed Sparse Row format>

In [36]:
ohe1.transform(dftw[["town"]]).toarray()

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.]])

In [37]:
ary1=ohe1.transform(dftw[["town"]]).toarray()

In [38]:
ary1

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.]])

In [39]:
ohe1.categories_


[array(['monroe township', 'robinsville', 'west windsor'], dtype=object)]

In [40]:
pd.DataFrame(ary1,columns=['monroe township', 'robinsville', 'west windsor'],dtype="int")

monroe township  robinsville  west windsor
0                 1            0             0
1                 1            0             0
2                 1            0             0
3                 1            0             0
4                 1            0             0
5                 0            0             1
6                 0            0             1
7                 0            0             1
8                 0            0             1
9                 0            1             0
10                0            1             0
11                0            1             0
12                0            1             0

In [41]:
df2=pd.DataFrame(ary1,columns=['monroe township', 'robinsville', 'west windsor'],dtype="int")

In [42]:
df2

monroe township  robinsville  west windsor
0                 1            0             0
1                 1            0             0
2                 1            0             0
3                 1            0             0
4                 1            0             0
5                 0            0             1
6                 0            0             1
7                 0            0             1
8                 0            0             1
9                 0            1             0
10                0            1             0
11                0            1             0
12                0            1             0

In [43]:
pd.concat([dftw,df2])

town    area     price  monroe township  robinsville  \
0   monroe township  2600.0  550000.0              NaN          NaN   
1   monroe township  3000.0  565000.0              NaN          NaN   
2   monroe township  3200.0  610000.0              NaN          NaN   
3   monroe township  3600.0  680000.0              NaN          NaN   
4   monroe township  4000.0  725000.0              NaN          NaN   
5      west windsor  2600.0  585000.0              NaN          NaN   
6      west windsor  2800.0  615000.0              NaN          NaN   
7      west windsor  3300.0  650000.0              NaN          NaN   
8      west windsor  3600.0  710000.0              NaN          NaN   
9       robinsville  2600.0  575000.0              NaN          NaN   
10      robinsville  2900.0  600000.0              NaN          NaN   
11      robinsville  3100.0  620000.0              NaN          NaN   
12      robinsville  3600.0  695000.0              NaN          NaN   
0               NaN     NaN       NaN              1.0          0.0   
1               NaN     NaN       NaN              1.0          0.0   
2               NaN     NaN       NaN              1.0          0.0   
3               NaN     NaN       NaN              1.0          0.0   
4               NaN     NaN       NaN              1.0          0.0   
5               NaN     NaN       NaN              0.0          0.0   
6               NaN     NaN       NaN              0.0          0.0   
7               NaN     NaN       NaN              0.0          0.0   
8               NaN     NaN       NaN              0.0          0.0   
9               NaN     NaN       NaN              0.0          1.0   
10              NaN     NaN       NaN              0.0          1.0   
11              NaN     NaN       NaN              0.0          1.0   
12              NaN     NaN       NaN              0.0          1.0   

    west windsor  
0            NaN  
1            NaN  
2            NaN  
3            NaN  
4            NaN  
5            NaN  
6            NaN  
7            NaN  
8            NaN  
9            NaN  
10           NaN  
11           NaN  
12           NaN  
0            0.0  
1            0.0  
2            0.0  
3            0.0  
4            0.0  
5            1.0  
6            1.0  
7            1.0  
8            1.0  
9            0.0  
10           0.0  
11           0.0  
12           0.0

In [45]:
pd.concat([dftw,df2],axis=1)

town  area   price  monroe township  robinsville  west windsor
0   monroe township  2600  550000                1            0             0
1   monroe township  3000  565000                1            0             0
2   monroe township  3200  610000                1            0             0
3   monroe township  3600  680000                1            0             0
4   monroe township  4000  725000                1            0             0
5      west windsor  2600  585000                0            0             1
6      west windsor  2800  615000                0            0             1
7      west windsor  3300  650000                0            0             1
8      west windsor  3600  710000                0            0             1
9       robinsville  2600  575000                0            1             0
10      robinsville  2900  600000                0            1             0
11      robinsville  3100  620000                0            1             0
12      robinsville  3600  695000                0            1             0

In [46]:
dftw=pd.concat([dftw,df2],axis=1)

In [47]:
dftw

town  area   price  monroe township  robinsville  west windsor
0   monroe township  2600  550000                1            0             0
1   monroe township  3000  565000                1            0             0
2   monroe township  3200  610000                1            0             0
3   monroe township  3600  680000                1            0             0
4   monroe township  4000  725000                1            0             0
5      west windsor  2600  585000                0            0             1
6      west windsor  2800  615000                0            0             1
7      west windsor  3300  650000                0            0             1
8      west windsor  3600  710000                0            0             1
9       robinsville  2600  575000                0            1             0
10      robinsville  2900  600000                0            1             0
11      robinsville  3100  620000                0            1             0
12      robinsville  3600  695000                0            1             0

In [49]:
dftw=dftw.drop("town",axis=1)

In [50]:
dftw

area   price  monroe township  robinsville  west windsor
0   2600  550000                1            0             0
1   3000  565000                1            0             0
2   3200  610000                1            0             0
3   3600  680000                1            0             0
4   4000  725000                1            0             0
5   2600  585000                0            0             1
6   2800  615000                0            0             1
7   3300  650000                0            0             1
8   3600  710000                0            0             1
9   2600  575000                0            1             0
10  2900  600000                0            1             0
11  3100  620000                0            1             0
12  3600  695000                0            1             0

In [51]:
dftw.columns

Index(['area', 'price', 'monroe township', 'robinsville', 'west windsor'], dtype='object')

In [52]:
dftw.reindex(columns=['monroe township', 'robinsville', 'west windsor','area', 'price'])

monroe township  robinsville  west windsor  area   price
0                 1            0             0  2600  550000
1                 1            0             0  3000  565000
2                 1            0             0  3200  610000
3                 1            0             0  3600  680000
4                 1            0             0  4000  725000
5                 0            0             1  2600  585000
6                 0            0             1  2800  615000
7                 0            0             1  3300  650000
8                 0            0             1  3600  710000
9                 0            1             0  2600  575000
10                0            1             0  2900  600000
11                0            1             0  3100  620000
12                0            1             0  3600  695000

In [54]:
dftw=dftw.reindex(columns=['monroe township', 'robinsville', 'west windsor','area', 'price'])

In [55]:
dftw

monroe township  robinsville  west windsor  area   price
0                 1            0             0  2600  550000
1                 1            0             0  3000  565000
2                 1            0             0  3200  610000
3                 1            0             0  3600  680000
4                 1            0             0  4000  725000
5                 0            0             1  2600  585000
6                 0            0             1  2800  615000
7                 0            0             1  3300  650000
8                 0            0             1  3600  710000
9                 0            1             0  2600  575000
10                0            1             0  2900  600000
11                0            1             0  3100  620000
12                0            1             0  3600  695000